services:
  web-client:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile.dev
    ports:
      - "${WEB_CLIENT_PORT:-3000}:3000"
    volumes:
      - ./apps/web-client:/app/apps/web-client
      - /app/apps/web-client/node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
